### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by tks65215** [tks65215/starostin#2]
- [x] make all necessary index page, css and js files.

- [ ]  remake adaptive menu;

- [x] добавить изюминку:

- [ ] add more animations and transitions;

- [x] add "Our services" section;

- [ ]  make php server;

- [ ] make replies section;

- [ ] make a universal CSS for fast adaptive layout
- [ ]  "About us" section redesign;
